apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        env:
        # --- CONEXIÓN A POSTGRES ---
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-auth
              key: postgres-password
        - name: DATABASE_URL
          value: "postgresql://admin:$(DB_PASSWORD)@postgres-service:5432/openwebui_db"

        # --- CONEXIÓN AL PROXY (LITELLM) ---
        - name: OPENAI_API_BASE_URL
          value: "http://litellm-service:4000/v1"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openwebui-auth
              key: proxy-key

        # --- CONFIGURACIÓN DE INTERFAZ ---
        - name: WEBUI_URL
          value: "https://ia.local"
        - name: WEBUI_NAME
          value: "IA Segura"
        - name: ENABLE_SIGNUP
          value: "true"
        - name: DEFAULT_USER_ROLE
          value: "pending"
        # --- PERSISTENCIA DE ARCHIVOS (RAG/LOGOS) ---
        volumeMounts:
        - name: open-webui-storage
          mountPath: /app/backend/data
      volumes:
      - name: open-webui-storage
        persistentVolumeClaim:
          claimName: open-webui-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
spec:
  selector:
    app: open-webui
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open-webui-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - host: ia.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: open-webui-service
            port:
              number: 8080
