apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: litellm-tls
  namespace: default                 # <-- ajusta si tu Ingress está en otro ns
spec:
  secretName: litellm-tls-secret    # <-- lo consume el Ingress
  dnsNames:
    - "{{ .Subdomain }}.kta41.local"   # ← variable que rellenaremos abajo
  issuerRef:
    name: kta-ca-issuer               # <-- nuestro ClusterIssuer global
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - digital signature
    - key encipherment
    - server auth
